service: utility
provider:
  name: aws
  runtime: go1.x
  region: ap-southeast-1

  ecr:
    images:
      utility:
        path: ../../.
        file: apps/utility/Dockerfile


functions:
  app:
    image:
      name: utility
    timeout: 30
    events:
      - http:
          method: any
          path: /{proxy+}
      - http:
          method: any
          path: /
