service: gate
provider:
  name: aws
  runtime: go1.x
  region: ap-southeast-1

  ecr:
    images:
      gate:
        path: ../../.
        file: apps/gate/Dockerfile


functions:
  app:
    image:
      name: gate
    timeout: 30
    events:
      - http:
          method: any
          path: /{proxy+}
      - http:
          method: any
          path: /
