service: account
provider:
  name: aws
  runtime: nodejs16.x
  region: ap-southeast-1
  environment:
    GOOGLE_APPLICATION_CREDENTIALS: ./google-services.json
    JWT_SECRET: auth-secret-1234

  ecr:
    images:
      account:
        path: ./
        file: account.Dockerfile

plugins:
  - serverless-offline

functions:
  app:
    image:
      name: account
      command:
        - dist/apps/account/main.handler
      entryPoint:
        - '/lambda-entrypoint.sh'
    timeout: 30
    events:
      - http:
          method: any
          path: /{proxy+}
      - http:
          method: any
          path: /