service: transactions
provider:
  name: aws
  runtime: go1.x
  region: ap-southeast-1


functions:
  app:
    handler: dist/apps/transactions
    timeout: 30
    events:
      - http:
          method: any
          path: /{proxy+}
      - http:
          method: any
          path: /
package:
  patterns:
    - '!*/**'
    - dist/apps/transactions