service: order
provider:
  name: aws
  runtime: go1.x
  region: ap-southeast-1

  ecr:
    images:
      order:
        path: ../../.
        file: apps/order/Dockerfile


functions:
  app:
    image:
      name: order
      command:
        - dist/apps/order
    timeout: 30
    events:
      - http:
          method: any
          path: /{proxy+}
      - http:
          method: any
          path: /
