service: order_v1
provider:
  name: aws
  runtime: go1.x
  region: ap-southeast-1

  ecr:
    images:
      order:
        path: ../../.
        file: apps/order_v1/Dockerfile


functions:
  app:
    image:
      name: order_v1
      command:
        - dist/apps/order_v1
    timeout: 30
    events:
      - http:
          method: any
          path: /{proxy+}
      - http:
          method: any
          path: /
