service: cart
provider:
  name: aws
  runtime: nodejs16.x
  region: ap-southeast-1
  environment:
    GOOGLE_APPLICATION_CREDENTIALS: ./google-services.json
    JWT_SECRET: auth-secret-1234

  ecr:
    images:
      cart:
        path: ../../.
        file: apps/cart/Dockerfile


functions:
  app:
    image:
      name: cart
    timeout: 30
    events:
      - http:
          method: any
          path: /{proxy+}
      - http:
          method: any
          path: /