// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD48SQUoAlU32Ryi_dm1Wr3GjnhYtGk150',
    appId: '1:319389880269:web:35bc6743ee7593101dfe84',
    messagingSenderId: '319389880269',
    projectId: 'lumajanglugo',
    authDomain: 'lumajanglugo.firebaseapp.com',
    storageBucket: 'lumajanglugo.appspot.com',
    measurementId: 'G-DXV71QRQYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOqC2IiY5GdegpRYJliVBYOOaLm-YjEvU',
    appId: '1:319389880269:android:fea05a9861a26dce1dfe84',
    messagingSenderId: '319389880269',
    projectId: 'lumajanglugo',
    storageBucket: 'lumajanglugo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1DxONCHTiZQfN4GRz9hvppede3mz7Sq4',
    appId: '1:319389880269:ios:a5307bd74f0725031dfe84',
    messagingSenderId: '319389880269',
    projectId: 'lumajanglugo',
    storageBucket: 'lumajanglugo.appspot.com',
    iosBundleId: 'com.example.lugoDriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1DxONCHTiZQfN4GRz9hvppede3mz7Sq4',
    appId: '1:319389880269:ios:24d11f36943b17a01dfe84',
    messagingSenderId: '319389880269',
    projectId: 'lumajanglugo',
    storageBucket: 'lumajanglugo.appspot.com',
    iosBundleId: 'com.example.lugoDriver.RunnerTests',
  );
}
