service: product
provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1
  environment:
    GOOGLE_APPLICATION_CREDENTIALS: ./google-services.json
    JWT_SECRET: auth-secret-1234

  ecr:
    images:
      product:
        path: ../../.
        file: apps/product/Dockerfile


functions:
  app:
    image:
      name: product
    timeout: 30
    events:
      - http:
          method: any
          path: /{proxy+}
      - http:
          method: any
          path: /