service: transactions
provider:
  name: aws
  runtime: go1.x
  region: ap-southeast-1

  ecr:
    images:
      transactions:
        path: ../../
        file: apps/transactions/Dockerfile


functions:
  app:
    image:
      name: transactions
    timeout: 30
    events:
      - http:
          method: any
          path: /{proxy+}
      - http:
          method: any
          path: /
